// <auto-generated />
using FlowerShopWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowerShopWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323161554_AddSeedTestData")]
    partial class AddSeedTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowerShopWebApplication.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Розы"
                        });
                });

            modelBuilder.Entity("FlowerShopWebApplication.Models.Flower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Классическая красная роза",
                            ImageUrl = "/img/rose_red.jpg",
                            Name = "Красная роза",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Нежная белая роза",
                            ImageUrl = "/img/rose_white.jpg",
                            Name = "Белая роза",
                            Price = 6.49m
                        });
                });

            modelBuilder.Entity("FlowerShopWebApplication.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlowerId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlowerId");

                    b.HasIndex("StoreId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlowerId = 1,
                            Quantity = 10,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 2,
                            FlowerId = 1,
                            Quantity = 5,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 3,
                            FlowerId = 2,
                            Quantity = 0,
                            StoreId = 1
                        });
                });

            modelBuilder.Entity("FlowerShopWebApplication.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StoreAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StoreAddress = "Ул Пушкина, дом калатушкина"
                        },
                        new
                        {
                            Id = 2,
                            StoreAddress = "ул Красная, дом 255"
                        });
                });

            modelBuilder.Entity("FlowerShopWebApplication.Models.Flower", b =>
                {
                    b.HasOne("FlowerShopWebApplication.Models.Category", "Category")
                        .WithMany("Flowers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FlowerShopWebApplication.Models.Inventory", b =>
                {
                    b.HasOne("FlowerShopWebApplication.Models.Flower", "Flower")
                        .WithMany("Inventories")
                        .HasForeignKey("FlowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowerShopWebApplication.Models.Store", "Store")
                        .WithMany("Inventories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flower");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("FlowerShopWebApplication.Models.Category", b =>
                {
                    b.Navigation("Flowers");
                });

            modelBuilder.Entity("FlowerShopWebApplication.Models.Flower", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("FlowerShopWebApplication.Models.Store", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
